In [7]:
import numpy as np

x = [1, 2, 3]
a = np.asarray(x)
print(a)

[1 2 3]


In [8]:
x = (1, 2, 3)
a = np.asarray(x)
print(a)

[1 2 3]


In [12]:
# 方法1：使用dtype=object创建对象数组
a = np.asarray(x, dtype=object)
print(a)

# 方法2：确保所有序列长度一致
x = [(1,2,3), (4,5,6)]  # 改为长度相同
a = np.asarray(x)

# 方法3：用None填充缺失位置
x = [(1,2,3), (4,5,None)]
a = np.array(x, dtype=float)
print(a)

[(1, 2, 3) (4, 5)]
[[ 1.  2.  3.]
 [ 4.  5. nan]]


In [ ]:
import numpy as np 
 
x =  [1,2,3] 
a = np.asarray(x, dtype =  float)  
print (a)

[1. 2. 3.]


In [10]:
import numpy as np 
 
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [ ]:
import numpy as np 

x =  [1,2,3] 
a = np.asarray(x, dtype =  float)  
print (a)

[1. 2. 3.]


In [15]:
import numpy as np 
 
# 使用 range 函数创建列表对象  
list=range(5)
it=iter(list)
 
# 使用迭代器创建 ndarray 
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]
