In [1]:
import numpy as np

x = np.arange(5)
print(x)

[0 1 2 3 4]


In [2]:
import numpy as np

x = np.arange(5, dtype = float)
print(x)

[0. 1. 2. 3. 4.]


In [3]:
import numpy as np
x = np.arange(5, 20, 2)
print(x)

[ 5  7  9 11 13 15 17 19]


In [4]:
np.linspace(0, 10, num = 50, endpoint = True)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [7]:
import numpy as np
a = np.linspace(1, 1, 10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
import numpy as np

a = np.linspace(10, 20, 5, endpoint = False)
print(a)

[10. 12. 14. 16. 18.]


In [9]:
import numpy as np

a = np.linspace(10, 20, 5, endpoint = True)
print(a)

[10.  12.5 15.  17.5 20. ]


In [13]:
import numpy as np
a = np.linspace(1, 10, 10, retstep = True)

print(a)
b = np.linspace(1, 10, 10).reshape([10, 1])
print(b)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), np.float64(1.0))
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


In [14]:
import numpy as np
# 默认底数是 10
a = np.logspace(1.0,  2.0, num =  10)  
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [15]:
import numpy as np
a = np.logspace(0,9,10,base=2)
print (a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


In [16]:
import numpy as np
a = np.logspace(0,9,10,base=2)
print (a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
