In [2]:
import numpy as np

a = np.arange(10)
s = slice(2, 7, 2)
print(a[s])

[2 4 6]


In [3]:
import numpy as np

a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


In [4]:
import numpy as np

a = np.arange(10)
b = a[5]
print(b)

5


In [6]:
import numpy as np

a = np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]
